// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contact struct {
	ID        uint64  `json:"id"`
	Name      string  `json:"name"`
	Text      string  `json:"text"`
	DeletedAt *string `json:"deletedAt,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Query struct {
}
